var OPERACION_LISTADO = 0;
var OPERACION_INCLUIR = 1;
var OPERACION_EDITAR = 2;
var OPERACION_ELIMINAR = 3;
var OPERACION_CONSULTAR = 4;
var OPERACION_CONSULTAR_CEDULA = 5;
var OPERACION_LISTADO_SOLO_PERSONAS = 6;
var OPERACION_LISTADO_MATERIALPOROBRA = 7;